project_id = "mqyoujkxhgwhgfwsqrgh"

[functions.collect-cvd]
verify_jwt = false

[functions.get-cvd-history]
verify_jwt = false

[functions.auto-collect-cvd]
verify_jwt = false

[functions.manage-monitored-coins]
verify_jwt = false

[functions.backfill-cvd-history]
verify_jwt = false