project_id = "mqyoujkxhgwhgfwsqrgh"

[functions.collect-cvd]
verify_jwt = false

[functions.get-cvd-history]
verify_jwt = false

[functions.auto-collect-cvd]
verify_jwt = false

# Cron job to auto-collect CVD data every 1 minute
[[edge_runtime.scheduler]]
enabled = true
cron = "* * * * *"  # 每1分钟执行一次
function_name = "auto-collect-cvd"
timeout = 60  # 60秒超时

[functions.manage-monitored-coins]
verify_jwt = false

[functions.backfill-cvd-history]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-alert]
verify_jwt = false

# Cron job: 每1分钟检查并发送Telegram警报
[[edge_runtime.scheduler]]
enabled = true
cron = "* * * * *"
function_name = "telegram-alert"
timeout = 60