import { Coin } from '@/types/coin';

// Binance Alpha 热门币种列表（持续更新）
export const BINANCE_ALPHA_COINS: Coin[] = [
  { base: 'APE', binance: 'APEUSDT' },
  { base: 'PENDLE', binance: 'PENDLEUSDT' },
  { base: 'WLD', binance: 'WLDUSDT' },
  { base: 'TIA', binance: 'TIAUSDT' },
  { base: 'SEI', binance: 'SEIUSDT' },
  { base: 'BLUR', binance: 'BLURUSDT' },
  { base: 'MEME', binance: 'MEMEUSDT' },
  { base: 'JTO', binance: 'JTOUSDT' },
  { base: 'PYTH', binance: 'PYTHUSDT' },
  { base: 'ACE', binance: 'ACEUSDT' },
  { base: 'NFP', binance: 'NFPUSDT' },
  { base: 'AI', binance: 'AIUSDT' },
  { base: 'PORTAL', binance: 'PORTALUSDT' },
  { base: 'PIXEL', binance: 'PIXELUSDT' },
  { base: 'STRK', binance: 'STRKUSDT' },
  { base: 'MANTA', binance: 'MANTAUSDT' },
  { base: 'ALT', binance: 'ALTUSDT' },
  { base: 'JUP', binance: 'JUPUSDT' },
  { base: 'WIF', binance: 'WIFUSDT' },
  { base: 'ETHFI', binance: 'ETHFIUSDT' },
  { base: 'BOME', binance: 'BOMEUSDT' },
  { base: 'ENA', binance: 'ENAUSDT' },
  { base: 'W', binance: 'WUSDT' },
  { base: 'TNSR', binance: 'TNSRUSDT' },
  { base: 'SAGA', binance: 'SAGAUSDT' },
  { base: 'TAO', binance: 'TAOUSDT' },
  { base: 'OMNI', binance: 'OMNIUSDT' },
  { base: 'REZ', binance: 'REZUSDT' },
  { base: 'BB', binance: 'BBUSDT' },
  { base: 'NOT', binance: 'NOTUSDT' },
  { base: 'IO', binance: 'IOUSDT' },
  { base: 'ZK', binance: 'ZKUSDT' },
  { base: 'ZRO', binance: 'ZROUSDT' },
  { base: 'LISTA', binance: 'LISTAUSDT' },
  { base: 'DOGS', binance: 'DOGSUSDT' },
  { base: 'TON', binance: 'TONUSDT' },
  { base: 'CATI', binance: 'CATIUSDT' },
  { base: 'HMSTR', binance: 'HMSTRUSDT' },
  { base: 'NEIRO', binance: 'NEIROUSDT' },
  { base: 'TURBO', binance: 'TURBOUSDT' },
  { base: 'EIGEN', binance: 'EIGENUSDT' },
  { base: 'GOAT', binance: 'GOATUSDT' },
  { base: 'PNUT', binance: 'PNUTUSDT' },
  { base: 'ACT', binance: 'ACTUSDT' },
  { base: 'USUAL', binance: 'USUALUSDT' },
  { base: 'MOVE', binance: 'MOVEUSDT' },
  { base: 'VANA', binance: 'VANAUSDT' },
  { base: 'ME', binance: 'MEUSDT' },
  { base: 'ORCA', binance: 'ORCAUSDT' },
];

export function getAlphaCoinSymbols(): string[] {
  return BINANCE_ALPHA_COINS.map(coin => coin.base);
}
